In [4]:
import numpy as np


GRID_SIZE = 5
START_STATE = (0, 0)
GOAL_STATE = (GRID_SIZE - 1, GRID_SIZE - 1)
ACTIONS = ['up', 'down', 'left', 'right']
NUM_ACTIONS = len(ACTIONS)


LEARNING_RATE = 0.8
DISCOUNT_FACTOR = 0.95
EXPLORATION_RATE = 0.1
NUM_EPISODES = 1000


q_table = np.zeros((GRID_SIZE, GRID_SIZE, NUM_ACTIONS))

def get_reward(state, next_state):
    if next_state == GOAL_STATE:
        return 100
    elif state == next_state:
        return -10
    else:
        return -1


def get_next_state(state, action):
    row, col = state
    if action == 'up':
        new_row = max(0, row - 1)
        return (new_row, col)
    elif action == 'down':
        new_row = min(GRID_SIZE - 1, row + 1)
        return (new_row, col)
    elif action == 'left':
        new_col = max(0, col - 1)
        return (row, new_col)
    elif action == 'right':
        new_col = min(GRID_SIZE - 1, col + 1)
        return (row, new_col)
    return state

def choose_action(state):
    if np.random.uniform(0, 1) < EXPLORATION_RATE:
        return np.random.choice(ACTIONS)
    else:
        row, col = state
        return ACTIONS[np.argmax(q_table[row, col, :])]

for episode in range(NUM_EPISODES):
    current_state = START_STATE
    done = False

    while not done:
        action = choose_action(current_state)
        action_index = ACTIONS.index(action)
        next_state = get_next_state(current_state, action)
        reward = get_reward(current_state, next_state)

        old_q_value = q_table[current_state[0], current_state[1], action_index]
        max_next_q = np.max(q_table[next_state[0], next_state[1], :])
        new_q_value = old_q_value + LEARNING_RATE * (reward + DISCOUNT_FACTOR * max_next_q - old_q_value)
        q_table[current_state[0], current_state[1], action_index] = new_q_value

        current_state = next_state

        if current_state == GOAL_STATE:
            done = True


optimal_policy = np.empty((GRID_SIZE, GRID_SIZE), dtype='U10')
for r in range(GRID_SIZE):
    for c in range(GRID_SIZE):
        optimal_policy[r, c] = ACTIONS[np.argmax(q_table[r, c, :])]

print("Q-table after training:")
print(q_table)
print("\nOptimal Policy:")
print(optimal_policy)

Q-table after training:
[[[ 50.61045175  63.80047553  50.61045175  63.80047553]
  [ 54.80047553  68.21102687  59.61045175  68.21102687]
  [ 45.7688215   72.8537125   61.10305778  -2.336     ]
  [ 49.48297     77.74075     -2.15168     -2.06208   ]
  [ -8.          -1.6         57.852634    -8.        ]]

 [[ -4.41934625  45.02926092  41.68204442  68.21102687]
  [ 63.80047553  72.8537125   63.80047553  72.8537125 ]
  [ 68.21102687  77.74075     68.21102687  77.74075   ]
  [ 72.8537125   82.885       72.8537125   82.88397264]
  [ -2.35392     88.3         77.74075     54.77504   ]]

 [[ 63.79622941  -3.18017536  -8.          -3.04256   ]
  [ 68.18832824  51.65670826  59.56130296  77.74075   ]
  [ 72.25150667  82.8849417   72.2479073   82.885     ]
  [ 77.74075     88.3         77.74075     88.3       ]
  [ 82.88499997  94.          82.885       79.3       ]]

 [[ -3.12513536  -2.9887488   -8.          60.81850626]
  [ 72.25244056  -2.428416    31.12828249  -2.428416  ]
  [ 61.731544    -